// Compiles a dependency that needs a toolchain and stores the result as
// third_party/prebuilt/<name>-<key>.tar.gz, which is checked into Git and
// unpacked by tools/vendor.js. Nothing here runs during normal development.
//
// usage: bun tools/prebuilt.js [--check] [--plan] [--missing] <name>... | --all
//   <name>     an artifact recipe declared in third_party/sources.js
//   --all      every artifact recipe
//   --missing  only recipes whose archive for the current key is absent
//   --check    build but do not write; fail if the result differs from the
//              checked-in archive. Running a build and then --check verifies
//              that the recipe is reproducible.
//   --plan     print the build plan instead of running it
//   --trace    echo every command the recipe and toolchain setups run
//
// The key names every input of the build (see tools/manifest.js). Editing a
// recipe, patch, source, option, toolchain or the container changes the key,
// and vendoring refuses to continue until the recipe has been rebuilt.
//
// Recipes run in the container built from third_party/recipes/Dockerfile (set
// CONVERT_TOOLCHAIN_IMAGE to use an already built image; CONVERT_DOCKER_NETWORK
// to pick a Docker network, e.g. host). third_party/ is mounted read-only; the
// plan generated from the manifest is mounted at /plan.sh; downloads, toolchain
// installations and compiler results live in Docker volumes shared by all
// builds (see recipes/run.sh). Remove them with:
//   docker volume rm convert-prebuilt-downloads convert-prebuilt-toolchains convert-prebuilt-ccache

import { randomUUID } from "node:crypto";
import {
  closeSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  openSync,
  readdirSync,
  readFileSync,
  renameSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, join, relative } from "node:path";
import { spawnSync } from "node:child_process";

import {
  allSources,
  artifactEntryName,
  artifactPath,
  entryKey,
  entrySources,
  patchesDir,
  platform,
  prebuiltDir,
  recipesDir,
  root,
  sha256,
  sources,
  thirdParty,
  toolchainKey,
  toolchains,
  toolchainsDir,
} from "./manifest.js";

const network = process.env.CONVERT_DOCKER_NETWORK
  ? ["--network", process.env.CONVERT_DOCKER_NETWORK]
  : [];

const args = process.argv.slice(2);
const check = args.includes("--check");
const planOnly = args.includes("--plan");
const all = args.includes("--all");
const missing = args.includes("--missing");
const trace = args.includes("--trace");
const names = args.filter((a) => !a.startsWith("--"));
for (const arg of args)
  if (
    arg.startsWith("--") &&
    !["--check", "--plan", "--all", "--missing", "--trace"].includes(arg)
  )
    throw new Error(`unknown option ${arg}`);
if (names.length === 0 && !all) {
  console.error(
    "usage: bun tools/prebuilt.js [--check] [--plan] [--missing] [--trace] <name>... | --all",
  );
  process.exit(2);
}
let entries = all
  ? sources.filter((entry) => entry.artifacts)
  : names.map((name) => {
      const entry = sources.find((entry) => entry.name === name);
      if (!entry?.build || !entry.artifacts)
        throw new Error(`no artifact recipe declared in sources.js: ${name}`);
      return entry;
    });
if (missing) {
  entries = entries.filter((entry) => !existsSync(artifactPath(entry)));
  if (entries.length === 0) {
    console.log("prebuilt: every archive is present for its current key");
    process.exit(0);
  }
}

// Paths inside the container.
const inContainer = (path) =>
  "/third_party" + path.slice(thirdParty.length).replaceAll("\\", "/");
const quote = (s) => `'${String(s).replaceAll("'", `'\\''`)}'`;

// The plan is a shell script over the steps defined in recipes/run.sh; it is
// the manifest, resolved for one recipe.
function plan(entry) {
  const lines = [
    `# ${entry.name} ${entryKey(entry)}`,
    "# generated by tools/prebuilt.js from third_party/sources.js",
  ];
  for (const name of entry.toolchains ?? []) {
    const toolchain = toolchains[name];
    const key = toolchainKey(name);
    lines.push(`if toolchain_missing ${quote(name)} ${key}; then`);
    for (const [source, { url, sha256, strip = 1 }] of Object.entries(
      allSources(name, toolchain),
    ))
      lines.push(
        `  toolchain_source ${quote(source)} ${quote(url)} ${sha256} ${strip}`,
      );
    lines.push(
      `  toolchain_setup ${quote(inContainer(join(toolchainsDir, toolchain.setup)))}`,
      "fi",
      `toolchain_use ${quote(name)} ${key}`,
    );
  }
  for (const [name, { url, sha256, strip = 1, patches = [] }] of Object.entries(
    entrySources(entry),
  )) {
    lines.push(`source_fetch ${quote(name)} ${quote(url)} ${sha256} ${strip}`);
    for (const patch of patches)
      lines.push(
        `source_patch ${quote(name)} ${quote(inContainer(join(patchesDir, patch)))}`,
      );
  }
  for (const [key, value] of Object.entries(entry.options ?? {}))
    lines.push(`export OPT_${key}=${quote(value)}`);
  lines.push(`build ${quote(inContainer(join(recipesDir, entry.build)))}`);
  return lines.join("\n") + "\n";
}

if (planOnly) {
  for (const entry of entries) process.stdout.write(plan(entry) + "\n");
  process.exit(0);
}

const container = `convert-prebuilt-${randomUUID()}`;

async function docker(args, stdout = "inherit") {
  const child = Bun.spawn(["docker", ...args], {
    stdin: "ignore",
    stdout,
    stderr: "inherit",
  });
  let cancelled = false;
  const cancel = () => {
    cancelled = true;
    child.kill("SIGKILL");
  };
  process.on("SIGINT", cancel);
  process.on("SIGTERM", cancel);
  try {
    const status = await child.exited;
    if (cancelled || status !== 0)
      throw new Error(
        `docker ${args[0]} failed (${cancelled ? "cancelled" : `exit ${status}`})`,
      );
  } finally {
    if (args[0] === "run")
      spawnSync("docker", ["rm", "-f", container], { stdio: "ignore" });
    process.off("SIGINT", cancel);
    process.off("SIGTERM", cancel);
  }
}

let image = process.env.CONVERT_TOOLCHAIN_IMAGE;
if (!image) {
  image = "convert-toolchain";
  await docker([
    "build",
    "--platform",
    platform,
    ...network,
    "-t",
    image,
    recipesDir,
  ]);
}

const scratch = mkdtempSync(join(tmpdir(), "prebuilt-"));
let failed = false;
try {
  for (const entry of entries) {
    const key = entryKey(entry);
    const archive = artifactPath(entry, key);
    const fresh = archive + ".new";
    const planFile = join(scratch, `${entry.name}.sh`);
    writeFileSync(planFile, plan(entry));
    console.log(`prebuilt: building ${entry.name} (${key})`);
    const options = [
      ["--init", "--name", container],
      ["--platform", platform],
      network,
      ["--volume", `${thirdParty}:/third_party:ro`],
      ["--volume", `${planFile}:/plan.sh:ro`],
      ["--volume", "convert-prebuilt-downloads:/downloads"],
      ["--volume", "convert-prebuilt-toolchains:/toolchains"],
      ["--volume", "convert-prebuilt-ccache:/ccache"],
      ["--env", "DOWNLOADS=/downloads"],
      ["--env", "TOOLCHAINS=/toolchains"],
      ["--env", "CCACHE_DIR=/ccache"],
      ["--env", "CCACHE_MAXSIZE=10G"],
      ["--env", "CCACHE_COMPILERCHECK=content"],
      trace ? ["--env", "TRACE=1"] : [],
      ["--workdir", "/build"],
    ].flat();
    mkdirSync(prebuiltDir, { recursive: true });
    const fd = openSync(fresh, "w");
    try {
      await docker(
        ["run", "--rm", ...options, image, "sh", "/third_party/recipes/run.sh"],
        fd,
      );
    } catch (error) {
      closeSync(fd);
      unlinkSync(fresh);
      throw error;
    }
    closeSync(fd);

    const before = existsSync(archive) ? sha256(readFileSync(archive)) : null;
    const after = sha256(readFileSync(fresh));
    const same = before === after;
    if (check) {
      unlinkSync(fresh);
      console.log(
        `prebuilt: ${entry.name} ${
          before === null
            ? "has no checked-in archive for this key"
            : same
              ? "reproduced the checked-in archive"
              : "DIFFERS from the checked-in archive"
        }`,
      );
      failed ||= !same;
    } else {
      renameSync(fresh, archive);
      // Archives for previous keys are obsolete.
      for (const file of readdirSync(prebuiltDir))
        if (
          artifactEntryName(file) === entry.name &&
          file !== basename(archive)
        )
          rmSync(join(prebuiltDir, file));
      console.log(
        `prebuilt: ${entry.name} -> ${relative(root, archive)} (${same ? "unchanged" : "updated"})`,
      );
    }
  }
} finally {
  rmSync(scratch, { recursive: true, force: true });
}
process.exit(failed ? 1 : 0);
